apiVersion: rhdh.redhat.com/v1alpha3
kind: Backstage
metadata:
  name: my-rhdh
spec:
  application:
    appConfig:
      mountPath: /opt/app-root/src
      configMaps:
        - name: my-rhdh-app-config
        - name: my-rhdh-db-config
    extraEnvs:
      secrets:
        - name: my-rhdh-secrets
        - name: rhdh-database-secret
  database:
    enableLocalDb: false
